# Generated by Django 5.0.4 on 2024-04-09 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.TextField()),
                ('message', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Coupen_code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=10, unique=True)),
                ('coupen_percentage', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('coupen_used', models.IntegerField(default=0)),
                ('used_user', models.CharField(blank=True, max_length=100)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('template_name', models.CharField(max_length=100)),
                ('template_img', models.ImageField(upload_to='orderimage')),
                ('template_id', models.TextField()),
                ('username', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('razorpay_order_id', models.CharField(blank=True, max_length=100)),
                ('razorpay_payment', models.CharField(blank=True, max_length=100)),
                ('finder', models.CharField(blank=True, max_length=100)),
                ('template_category', models.TextField(blank=True)),
                ('template_amount', models.TextField()),
                ('coupen_code', models.CharField(blank=True, max_length=20, null=True)),
                ('final_amount', models.IntegerField(default=0)),
                ('plan', models.CharField(blank=True, default=True, max_length=20)),
                ('amount_paid', models.BooleanField(default=False)),
                ('host_name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PaymentFailed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=250)),
                ('reason', models.CharField(max_length=250)),
                ('code', models.CharField(max_length=250)),
                ('source', models.CharField(max_length=250)),
                ('step', models.CharField(max_length=250)),
                ('payment_id', models.CharField(max_length=250)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TemplatesType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('slug', models.SlugField(max_length=40, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentSuccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('expiry_date', models.DateTimeField()),
                ('countdown', models.IntegerField(default=0)),
                ('payment_status', models.BooleanField(default=False)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mainapp.orders')),
            ],
        ),
        migrations.CreateModel(
            name='Renewal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expiry_date', models.DateTimeField()),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('reminder_date', models.DateTimeField()),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mainapp.orders')),
                ('payment_success', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.paymentsuccess')),
            ],
        ),
        migrations.CreateModel(
            name='Templates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('find', models.CharField(max_length=40)),
                ('category', models.CharField(max_length=40)),
                ('temp_img', models.ImageField(upload_to='temp_meadia')),
                ('temp_file', models.FileField(upload_to='templates')),
                ('price', models.IntegerField()),
                ('temp_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.templatestype')),
            ],
        ),
    ]
