# Generated by Django 5.0.4 on 2024-04-11 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0003_alter_deleteverificationtoken_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailverificationtoken',
            name='user',
        ),
        migrations.DeleteModel(
            name='DeleteVerificationToken',
        ),
        migrations.DeleteModel(
            name='EmailVerificationToken',
        ),
    ]
