# Generated by Django 5.0.4 on 2024-04-11 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0005_deleteverificationtoken_emailverificationtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='cuid',
            field=models.IntegerField(unique=True),
        ),
    ]
