# Generated by Django 5.0.4 on 2024-05-08 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0008_alter_customuser_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.TextField(blank=True, default='123 123 1235'),
        ),
    ]
